Add 1 example
nim-lang/website pull request #293
Opened 2021-08-12 13:44 UTC by juancarlospaco

- Add 1 example about ranges, tiny diff.

2021-08-12 19:07 UTC, dom96 requested changes
Dunno if we should add it, it just looks too much like a test suite for ranges. Maybe a short and sweet example would be better?

2021-08-12 19:07 UTC, dom96 commented on jekyll/code_carrousel.html
> +# float range, value must be between '3.3' and '7.5'.
```suggestion

# float range, value must be between '3.3' and '7.5'.
```

2021-08-12 19:07 UTC, dom96 commented on jekyll/code_carrousel.html
> +# char range, value must be between 'b' and 'f'.
```suggestion

# char range, value must be between 'b' and 'f'.
```

2021-08-12 19:07 UTC, dom96 commented on jekyll/code_carrousel.html
> +# Positive, value must be > 0.
```suggestion

# Positive, value must be > 0.
```

2021-08-12 19:07 UTC, dom96 commented on jekyll/code_carrousel.html
> +# Natural, value must be >= 0.
```suggestion

# Natural, value must be >= 0.
```

2021-08-18 17:56 UTC, juancarlospaco commented
It is 2 `assert` each range, is not too much, and people are asking for more examples. 😐

2021-08-23 08:04 UTC, narimiran commented
> it just looks too much like a test suite for ranges. Maybe a short and sweet example would be better?

I agree, it is too long/boring. Just keep int range, char range and `Natural`.

2021-08-23 12:44 UTC, closed without merging